# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='property.Property'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.Property'),
        ),
        migrations.AlterField(
            model_name='review',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='property.Property'),
        ),
        migrations.AlterField(
            model_name='specialrate',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_rates', to='property.Property'),
        ),
        migrations.AlterField(
            model_name='unavailabledate',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='property.Property'),
        ),
    ]
