# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20170426_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_embed_src',
            field=models.CharField(default='', max_length=600),
        ),
    ]
