# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20170504_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailabledate',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Booking'),
        ),
        migrations.AlterField(
            model_name='unavailabledate',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='property.Property'),
        ),
    ]
