# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20170505_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='specialrate',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='unavailabledate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
